todolist/todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_list, name='add_list'),
    path('edit/<int:todolist_id>/', views.edit_list, name='edit_list'),
    path('delete/<int:todolist_id>/', views.delete_list, name='delete_list'),
    path('<int:todolist_id>/', views.view_list, name='view_list'),
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('<int:question_id>/results/', views.results, name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todolist/todo/models.py
import datetime

from django.db import models
from django.utils import timezone


class List(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    date_add = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    startdate = models.DateField()
    enddate = models.DateField()

todolist/todo/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.template import loader
from django.contrib import messages

from .models import List


def index(request):
    todo_list = List.objects.order_by('date_modified')
    context = {'lists': todo_list}
    return render(request, 'todo/index.html', context)


def add_list(request):
    if request.method == 'POST':
        todo = List(
            title=request.POST['title'],
            description=request.POST['description'],
            startdate=request.POST['startdate'],
            enddate=request.POST['enddate']
        )
        todo.save()
        return redirect('todo:index')
    return render(request, 'todo/todolist.html')


def edit_list(request, todolist_id):
    todo = List.objects.get(id=todolist_id)
    if request.method == 'POST':
        todo.title=request.POST['title']
        todo.description=request.POST['description']
        todo.startdate=request.POST['startdate']
        todo.enddate=request.POST['enddate']
        todo.save()
        return redirect('todo:index')
    context = {'list': todo}
    return render(request, 'todo/todolist.html', context)


def delete_list(request, todolist_id):
    List.objects.filter(id=todolist_id).delete()
    return redirect('todo:index')


def view_list(request, todolist_id):
    todo = List.objects.get(id=todolist_id)
    context = {'list': todo}
    return render(request, 'todo/detail.html', context)

todolist/todo/templates/todo/detail.html
{% extends "todo/index.html" %}

{% load static %}

{% block body %}
</div>
<h2>{{ list.title }}</h2>
<p>{{ list.description }}</p>
<p>Start : {{ list.startdate }}</p>
<p>End : {{ list.enddate }}</p>
<a class="btn btn-success" href="{% url 'todo:edit_list' list.id %}">Edit</a>
<a class="btn btn-danger" href="{% url 'todo:delete_list' list.id %}">Delete</a>
{% endblock %}

todolist/todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TodoList</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    {% load static %}
    <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" type='text/css' href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    {% block css %}{% endblock %}

    <!-- Scripts
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/js.js' %}"></script>
    {% block js %}{% endblock %}
</head>

<body>
    <div class="container">
        <div style="position: relative;">
            <h1><a href="{% url 'todo:index' %}">TodoList</a></h1>
        {% block body %}
            <a id="add" class="btn btn-primary" href="{% url 'todo:add_list' %}">Add</a>
        </div>
        <table class="table table-striped">
            <thead class='thead-dark'>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col" class="list_title">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col" class="list_date">Startdate</th>
                    <th scope="col" class="list_date">Enddate</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for list in lists %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ list.title }}</td>
                    <td class="list_desc">{{ list.description }}</td>
                    <td>{{ list.startdate }}</td>
                    <td>{{ list.enddate }}</td>
                    <td><a class="far fa-eye" href="{% url 'todo:view_list' list.id %}" data-toggle="tooltip" title="View"></a><a class="far fa-edit" href="{% url 'todo:edit_list' list.id %}" data-toggle="tooltip" title="Edit"></a><a class="far fa-trash-alt" href="{% url 'todo:delete_list' list.id %}" data-toggle="tooltip" title="Delete"></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endblock %}
    </div>
</body>

</html>

todolist/todo/templates/todo/todolist.html
{% extends "todo/index.html" %}

{% load static %}

{% block body %}
</div>
{% if list %}
<form action="{% url 'todo:edit_list' list.id %}" method=post>
{% else %}
<form action="{% url 'todo:add_list' %}" method=post>
{% endif %}
    {% csrf_token %}
    <div class="form-group">
        <label>Title</label>
        <input name="title" type="text" class="form-control" placeholder="Title" required value="{{ list.title }}">
    </div>
    <div class="form-group">
        <label>Description</label>
        <textarea name="description" class="form-control" rows="7" required>{{ list.description }}</textarea>
    </div>
    <div class="form-group">
        <label>Start Date</label>
        <input name="startdate" type="date" class="form-control" required value="{{ list.startdate|date:'Y-m-d' }}">
    </div>
    <div class="form-group">
        <label>End Date</label>
        <input name="enddate" type="date" class="form-control" required value="{{ list.enddate|date:'Y-m-d' }}">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}